DO_table = {
    'GET':{
        0x0101: {'description': '0-max. Optional private use DO 1.', 'type': 'S', },
        0x0102: {'description': '0-max. Optional private use DO 2.', 'type': 'S', },
        0x0103: {'description': '0-max. Optional private use DO 3.', 'type': 'S', },
        0x0104: {'description': '0-max. Optional private use DO 4.', 'type': 'S', },
        0x004F: {'description': '5-16. Full AID.', 'type': 'S', },
        0x005E: {'description': '0-max. Login data, proprietary.', 'type': 'S', },
        0x5F50: {'description': '0-max. Uniform resource locator, URL to set of OpenPGP public keys.', 'type': 'S', },
        0x5F52: {'description': '0-15.  Historical bytes.', 'type': 'S', },
        0x7F66: {'description': '8. Extended length information.', 'type': 'C', },
        0x7F74: {'description': '3. Optional general feature management.', 'type': 'C', },
        0x0065: {'description': 'var. Cardholder related data.', 'type': 'C', },
        0x005B: {'description': '0-39. Name.', 'type': 'S', },
        0x5F2D: {'description': '2-8. Language preferences.', 'type': 'S', },
        0x5F35: {'description': '1. Sex.', 'type': 'S', },
        0x006E: {'description': 'var. Application Related Data.', 'type': 'C', },
        # {'description': 0x004F:. 5-16. Application identifier AID.', 'type': 'S', },
        0x0073: {'description': 'var. Discretionary data objects.', 'type': 'C', },
        0x00C0: {'description': '10. Extended capabilities.', 'type': 'S', },
        0x00C1: {'description': 'var. Algorithm attributes signature.', 'type': 'S', },
        0x00C2: {'description': 'var. Algorithm attributes decryption.', 'type': 'S', },
        0x00C3: {'description': 'var. Algorithm attributes authentication.', 'type': 'S', },
        0x00C4: {'description': '7. PW status Bytes (PW1, PW1 max length, RC max length, PW3 max length, ...)', 'type': 'S', },
        0x00C5: {'description': '60. fingerprints, 20 bytes each for sig,dec,auth.', 'type': 'S', },
        0x00C6: {'description': '60. CA fingerprints, 20 bytes each.', 'type': 'S', },
        0x00CD: {'description': '12. List of 3, 4-byte dates for pubkey pairs.', 'type': 'S', },
        0x00D6: {'description': '2. Optional User interaction flag for PSO:CDS.', 'type': 'S', },
        0x00D7: {'description': '2. Optional User interaction flag for PSO:DEC.', 'type': 'S', },
        0x00D8: {'description': '2. Optional User interaction flag for PSO:AUTH.', 'type': 'S', },

        0x007A: {'description': '5. Security support template.', 'type': 'C', },
        0x0093: {'description': '3. Digital signature counter.', 'type': 'S', },
        0x7F21: {'description': '0-max. Cardholder certificates (AUT, DEC, SIG).', 'type': 'C', },
    },
    'PUT':{
        0x0101: {'description': '0-max. Optional private use DO 1.', 'type': 'S', },
        0x0102: {'description': '0-max. Optional private use DO 2.', 'type': 'S', },
        0x0103: {'description': '0-max. Optional private use DO 3.', 'type': 'S', },
        0x0104: {'description': '0-max. Optional private use DO 4.', 'type': 'S', },
        0x004D: {'description': 'var. Extended header list (used for optional key import).', 'type': 'C', },

        0x7F48: {'description': 'Cardholder private key template', 'type': 'C', 'template': True},
        0x0091: {'description': 'Public exponent e', 'type': 's', },
        0x0092: {'description': 'Prime 1: p', 'type': 's', },
        0x0093: {'description': 'Prime 2: q', 'type': 's', },
        0x0094: {'description': 'PQ: 1/q mod p', 'type': 's', },
        0x0095: {'description': 'DP1: d mod(p-1)', 'type': 's', },
        0x0096: {'description': 'DQ1: d mod(q-1)', 'type': 's', },
        0x0097: {'description': 'modulus n', 'type': 's', },

        0x5F48: {'description': 'Concatenation of keydata', 'type': 'S', },

        0x3FFF: {'description': 'var. Extended header list (used for optional key import).', 'type': 'C', },
        0x005E: {'description': '0-max. Login data, proprietary.', 'type': 'S', },
        0x5F50: {'description': '0-max. Uniform resource locator, URL to set of OpenPGP public keys.', 'type': 'S', },
        
        0x005B: {'description': '0-39. Name.', 'type': 'S', },
        0x5F2D: {'description': '2-8. Language preferences.', 'type': 'S', },
        0x5F35: {'description': '1. Sex.', 'type': 'S', },
        0x006E: {'description': 'var. Application Related Data.', 'type': 'C', },
        0x7F21: {'description': '0-max. Cardholder certificates (AUT, DEC, SIG).', 'type': 'C', },

        # 0x004F: 'S. 5-16. Applition identifier AID.',
        0x00C1: {'description': 'var. Algorithm attributes signature.', 'type': 'S', },
        0x00C2: {'description': 'var. Algorithm attributes decryption.', 'type': 'S', },
        0x00C3: {'description': 'var. Algorithm attributes authentication.', 'type': 'S', },
        0x00C4: {'description': '7. PW status Bytes (PW1, PW1 max length, RC max length, PW3 max length, ...)', 'type': 'S', },
        0x00C7: {'description': '20. sig key fingerprint.', 'type': 'S', },
        0x00C8: {'description': '20. dec key fingerprint.', 'type': 'S', },
        0x00C9: {'description': '20. auth key fingerprint.', 'type': 'S', },
        0x00CA: {'description': '20. 1st CA fingerprint in list.', 'type': 'S', },
        0x00CB: {'description': '20. 2nd CA fingerprint in list.', 'type': 'S', },
        0x00CC: {'description': '20. 3rd CA fingerprint in list.', 'type': 'S', },
        0x00CE: {'description': '4. Generation date for signature key.', 'type': 'S', },
        0x00CF: {'description': '4. Generation date for decryption key.', 'type': 'S', },
        0x00D0: {'description': '4. Generation date for authentication key.', 'type': 'S', },

        0x00D1: {'description': '16/32. Optional SM-Key-ENC for cryptogram.', 'type': 'S', },
        0x00D2: {'description': '16/32. Optional SM-Key-MAC for cryptographic checksum.', 'type': 'S', },
        0x00D3: {'description': '0-8 - xx. Resetting code.', 'type': 'S', },
        0x00D5: {'description': '16/32. Optional PSO:DEC with AES.', 'type': 'S', },

        0x00D6: {'description': '2. Optional User interaction flag for PSO:CDS.', 'type': 'S', },
        0x00D7: {'description': '2. Optional User interaction flag for PSO:DEC.', 'type': 'S', },
        0x00D8: {'description': '2. Optional User interaction flag for PSO:AUTH.', 'type': 'S', },

        0x00F4: {'description': 'var. Optional container for both SM keys (ENC, MAC).  For simulataneous update.', 'type': 'C', },
    }
}